#pragma once

// SYSTEM PARAMETERS
#define NUM_FLOORS 8
#define DOOR_WAIT_SECONDS 1

// HW COMPONENTS CONSTANTS
// ---- Floors IO
#define FLOORS_REGISTERS_SIZE 8
// ---- Lift Motor
#define LM_STEPS_PER_REVOLUTION 90
#define LM_RPM 12
// ---- Door Motor
#define DM_STEPS_PER_REVOLUTION 90
#define DM_RPM 12
#define CLOSED_DOOR_STEP DM_STEPS_PER_REVOLUTION/2
#define OPENED_DOOR_STEP 0
// ---- Ultrasonic
#define OBSTALCE_DISTANCE_THRESHOLD_CM 200

// PINS
#define US_PING_PIN 4
#define US_ECHO_PIN 5

#define DOOR_MOTOR_PIN1 6
#define DOOR_MOTOR_PIN2 7
#define DOOR_MOTOR_PIN3 8
#define DOOR_MOTOR_PIN4 9

#define LIFT_MOTOR_PIN1 10
#define LIFT_MOTOR_PIN2 11
#define LIFT_MOTOR_PIN3 12
#define LIFT_MOTOR_PIN4 13

#define FLOORS_REGISTERS_CLOCK A0
#define FLOORS_REGISTERS_LATCH A1
#define FLOORS_UP_PIN A2
#define FLOORS_DOWN_PIN A3
#define FLOORS_IR_PIN A4

#define ELEVATOR_NUMPAD_PIN A5