#pragma once

// SYSTEM PARAMETERS
#define NUM_FLOORS 8
#define DOOR_WAIT_SECONDS 1
#define DIRECTION_REVERSE_SECONDS 1

// HW COMPONENTS CONSTANTS
// ---- 7 Segment Output
#define SEVEN_SEGMENT_REGISTERS_SIZE 8
// ---- Floors Inputs
#define FLOORS_REGISTERS_SIZE 8
// ---- Keypad
#define KEYPAD_ROWS_REGISTER_SIZE 8
#define KEYPAD_COLS_REGISTER_SIZE 8
#define KEYPAD_ROW_NUM 4
#define KEYPAD_COLUMN_NUM 3
// ---- Lift Motor
#define LM_STEPS_PER_REVOLUTION 20
#define LM_RPM 60
// ---- Door Motor
#define DM_STEPS_PER_REVOLUTION 20
#define DM_RPM 60
#define CLOSED_DOOR_STEP DM_STEPS_PER_REVOLUTION/2
#define OPENED_DOOR_STEP 0
// ---- Ultrasonic
#define OBSTALCE_DISTANCE_THRESHOLD_CM 200

// PINS
#define KEYPAD_IN_LATCH 2
#define SEV_SEGMENT_REGISTER_LATCH 3

#define US_PING_PIN 4
#define US_ECHO_PIN 5

#define SEV_SEGMENT_REGISTER_DATA 6

#define KEYPAD_OUT_PIN 7
#define KEYPAD_OUT_LATCH 8

#define MOTOR_PIN1 10
#define MOTOR_PIN2 11
#define MOTOR_PIN3 12
#define MOTOR_PIN4 13

#define MOTORS_SELECTOR_PIN 9

#define DOOR_MOTOR  0
#define LIFT_MOTOR  1

#define REGISTERS_CLOCK A0
#define FLOORS_INPUT_LATCH A1
#define FLOORS_UP_PIN A2
#define FLOORS_DOWN_PIN A3
#define FLOORS_IR_PIN A4

#define KEYPAD_IN_PIN A5
